[package]
name = "Data_Fetcher_assignment"
version = "0.1.0"
edition = "2021"

[dependencies]
ureq = { version = "2.9.1", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"